export default {
  MAP: 'MAP',
  POINT_NAME_INPUT: 'POINT_NAME_INPUT',
  ADD_POINT_BUTTON: 'ADD_POINT_BUTTON',
  POINTS_LIST_ITEM: 'POINTS_LIST_ITEM',
  DELETE_LIST_ITEM_BUTTON: 'DELETE_LIST_ITEM_BUTTON',
};
